# STUDENTS SHOULD QUERY OUR DB FOR DATA AND SAVE IN VARIBALES

# DATA SHOULD THEN BE MANIUPULATED IN VARIOUS WAYS TO FIT NEW DB SCHEMA
# WE WANT TO SEE GOOD TDD FOR THIS

# MANIUPULATED DATA SHOULD THEN BE INSERTED IN CORRECT ORDER
# DO WE WANT THEM TO FIGURE OUT ORDER OR GIVE THEM THE ORDER?
